# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def pods
    use_frameworks!

    pod 'RestBird/Alamofire'
    pod 'IHProgressHUD'
    pod 'Starscream', '~> 3.0.2'
    pod 'Reusable'
    pod 'RealmSwift'
end

target 'Exam' do
  pods
end

target 'Exam-Clerk' do
    pods
end
